#include <iostream>
int main(){
    using namespace std;
    const int ArSize = 20;
    char name[ArSize];
    char dessert[ArSize];

    cout <<"Enter your name: \n";
    cin.getline(name, ArSize); //reads through the whole line
    cout << "Enter dessert: \n";
    cin.getline(dessert, ArSize);

    //cin getlin responds by reading the name all the way until the newline char(generated by hitting enter) => then converts it to null

    cout << "I have some delicious " <<dessert;
    cout <<" for you "<<name;
    return 0;
}